version: '3.8'

services:
  mongodb:
    build: ./db
    env_file:
      - .env
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend_network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    depends_on:
      - mongodb
    environment:
        PYTHONNUNBUFFERED: 1
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./backend:/backend
    networks:
      - backend_network
      - frontend_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-config logging_config.ini

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - frontend_network

volumes:
  mongodb_data:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
